# docker-compose.yml

version: '3'

services:
  nginx:
    build: ./NGINX
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./NGINX/certs:/etc/letsencrypt/live/labnvh.online
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf
  tcp_server:
    build: ./TCP-SERVER
    ports:
      - "8081:8081"
  opc_server:
    build: ./OPC-SERVER
    ports:
      - "4840:4840"



